### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by apwiggins** [KaisenAmin/c_std#1]
Nice work!  Added a standard compile chain to have a look but doesn't compile "as is".  Feel free to borrow.

# Dockerfile: builder.Dockerfile

```
ARG base_tag=bullseye
ARG base_img=mcr.microsoft.com/vscode/devcontainers/base:dev-${base_tag}

FROM --platform=linux/amd64 ${base_img} AS builder-install

RUN apt-get update --fix-missing && apt-get -y upgrade
RUN apt-get install -y --no-install-recommends \
    apt-utils \
    curl \
    cmake \
    build-essential \
    gcc \
    gdb \
    g++-multilib \
    locales \
    make \
    ruby \
    gcovr \
    wget \
    python3 \
    && rm -rf /var/lib/apt/lists/*
```

# Makefile:

```
# project 
project_name=c_std

builder-build :
	docker build \
                    -f builder.Dockerfile 
                    -t ${project_name}-builder:latest .

builder-run :
	docker run \
		--rm \
		-it \
		--platform linux/amd64 \
		--workdir /builder/mnt \
		-v ${PWD}:/builder/mnt \
		${project_name}-builder:latest \
		/bin/bash
                #/bin/bash -c "python3 compile.py b"

```

# Compile:

```
make builder-build
make builder-run

(container) python3 compile.py b
```

# Output:

```
...truncated...
file_io/file_writer.c: In function ‘file_writer_lock’:
file_io/file_writer.c:494:15: warning: implicit declaration of function ‘fileno’ [-Wimplicit-function-declaration]
  494 |     if (fcntl(fileno(writer->file_writer), F_SETLKW, &fl) == -1) {
      |               ^~~~~~
file_io/file_writer.c: In function ‘file_writer_truncate’:
file_io/file_writer.c:580:9: warning: implicit declaration of function ‘ftruncate’; did you mean ‘strncat’? [-Wimplicit-function-declaration]
  580 |     if (ftruncate(fd, size) == -1) {
      |         ^~~~~~~~~
      |         strncat
Compilation failed.
```

**Comment by KaisenAmin** [comment]
1 - Feature Test Macros: In some Unix-like systems, including certain function prototypes from headers like <unistd.h> requires defining specific feature test macros. This is especially relevant for functions that are part of the POSIX standard but not part of the C standard library itself. Add the following line at the top of your file_writer.c file (before any includes)

#define _POSIX_C_SOURCE 200809L

2 -  Ensure that your compiler and linker flags are not inadvertently causing these functions to be omitted. For example, strict ANSI mode might exclude non-ANSI functions. Review the flags used in your compilation process for anything that might restrict available functions.

3 - To confirm whether this is an issue specific to the Docker environment, try compiling the code on a different Unix-like system or environment. If it compiles without warnings elsewhere, it points to a configuration issue within the Docker environment. 

4 - also please check that docker have all the necessary standard libraries and headers installed. packages like libc6-dev or build-essential .

Compiling with Cmake will come soon.
I will do the configuration as soon as possible.

**Comment by apwiggins** [comment]
The point that I was trying to make (unsuccessfully) related to having one or more standard compile chains as Dockerfiles in this git repository so that the end-to-end reference compile chain(s) are visible to everyone (i.e., no looking for libraries, since they're part of the reference Dockerfile).  It will help your smoke test process as well since each reference compile chain in succession could be triggered by github actions.
