### ISSUE TITLE
No Trie yet

### ISSUE THREAD

**Issue by jdefrancesco** [KaisenAmin/c_std#11]
I noticed there is no Trie (prefix tree) module yet. I am almost finished writing one then I'll initiate a PR. Apologize for any time lag in advance, I work on it when day job isn't occupying all my time.

**Comment by KaisenAmin** [comment]
I'm truly delighted to hear that you're working on adding a Trie module to
the project and I appreciate your efforts. There's no worry about any
delays; we all have our commitments, and the fact that you're dedicating
your time to improve this project is incredibly valuable. I'm patiently and
eagerly looking forward to seeing your work in the project. Please, do not
hesitate to reach out to me if you need any assistance or feedback.
