### ISSUE TITLE
You should change the title & description

### ISSUE THREAD

**Issue by ha-ves** [KaisenAmin/c_std#12]
# The description of this project is clickbaity and misleading.

### Please change the description to better address this, you can change to the similarities of "Basic C++ libraries for C", just don't put "THE STANDARD".

**Comment by KaisenAmin** [comment]
I completely agree with you, my friend, that this project has numerous
issues and a long way to go in terms of performance and many other aspects
before it can compare to the C++ standard library (std C++). However, my
efforts are aligned in that direction.
A few points must not be forgotten: we are coding in C, not C++. We lack
many features of C++. I've started this project solo about 6 months ago,
but C++ has been evolving its standard library for at least 30 years;
naturally, it's much better.
But I think it's still valid to refer to it as an implementation of the std
in C. For instance, when we talk about artificial intelligence, does
computer-based intelligence really resemble the way our brains work, or our
intelligence, with all its immense complexity? Yet, we still refer to it.

**Comment by ha-ves** [comment]
### Yes, you can provide an implementation of Cpp-like objects, but you cannot name it "**C++ standard for C**" which your repository implies. If it was a **wrapper** then it's functionally correct, but it's not.

### If you value your effort, don't try to reinvent the wheel, put effort into improving the wheel. There were reasons they kept C & C++ from overspilling into one another.

### And No, you can not just put AI into this conversation because it has nothing to do with this repository.

### Last ask: Please rename it to the similarities of "**Basic C++ for C**"

**Comment by KaisenAmin** [comment]
OK, I promise to change the name, I will definitely think about your suggestion But I need an opportunity to be able to name it properly.
