### ISSUE TITLE
[bug log] the fmt library 

### ISSUE THREAD

**Issue by rovinax** [KaisenAmin/c_std#20]
### Platform Ubuntu22.04
Hi, when I test your code I find a good way to solve it without use the `FMT_END_ARGS` in `fmt.c` locate in `fmt_print` and `fmt_println`.
### Recurrence
when i use the api , i don't want to use it with the define `FMT_END_ARGS` just like the following code.
```
int main() {
    const char* str = "Hello, World!";
    fmt_println(str);
    return 0;
}
```
the output is
```
Compilation successful. Output: ./build/main
Running the program...
*************************
Hello, World! �L�� �L�� @!�I�U  ��UH��AWAVAUATSH��8L�%�I 
```
### How to Fix it
There is a high probability that garbled characters appear because you cannot use simple define va_arg() to show all **parameter list** in C code. It causes undefined behavior.

**Comment by rovinax** [comment]
Maybe use the define function will solve it.
![image](https://github.com/KaisenAmin/c_std/assets/116474341/b9caa5da-4142-4c08-8f38-a8be0d87ceaf)
![image](https://github.com/KaisenAmin/c_std/assets/116474341/d56d77aa-21bc-4ef7-aa7c-ef2840a4fc30)
it works in my linux system.

**Comment by KaisenAmin** [comment]
Hi,

Apologies for the delayed response. This issue has now been resolved, and there's no longer a need to use FMT_END_ARGS. I've corrected all the examples.
![1](https://github.com/KaisenAmin/c_std/assets/37073193/0435286b-ba12-4cfb-b7e9-19ddfa1dd6e8)
![2](https://github.com/KaisenAmin/c_std/assets/37073193/f995808a-f217-4c16-8d36-1cf792dfba36)

Thanks,
