### ISSUE TITLE
Multiple issues with arrays and vectors "push_back,emplace_back" in multiple files

### ISSUE THREAD

**Issue by HelifeWasTaken** [KaisenAmin/c_std#3]
I may add all issues about `vector_push_back,vector_emplace_back` and related for reference to check

```cpp
// json.c:789
        case JSON_ARRAY:
            for (size_t i = 0; i < vector_size(element->value.array_val); ++i) {
                JsonElement *item = json_deep_copy(*(JsonElement **)vector_at(element->value.array_val, i));
                if (!item) {
                    json_deallocate(copy);
                    return NULL;
                }
                vector_push_back(copy->value.array_val, &item);
            }
            break;
```
What is expected here for example if `vector_push_back` fails ? Should not we free all the copied data and return `NULL` ?
Because user may have a error message but nothing is recoverable from here...

**Comment by KaisenAmin** [comment]
Dear Mattis,

I've reviewed your notation in the Vector and Json components, and you're
absolutely correct. Based on your insights, I've made significant changes
to the vector_push_back and json_deep_copy functions.

The vector_push_back function now returns a boolean value to indicate
success or failure.

case JSON_ARRAY:
    for (size_t i = 0; i < vector_size(element->value.array_val); ++i) {
        JsonElement *item = json_deep_copy(*(JsonElement
**)vector_at(element->value.array_val, i));
        if (!item) {
            json_deallocate(copy);
            return NULL;
        }
        if (!vector_push_back(copy->value.array_val, &item)) {
            json_deallocate(item);
            json_deallocate(copy); // Clean up any previously copied items
            return NULL; // Failure to push back results in a NULL return
        }
    }
    break;

bool vector_push_back(Vector *vec, const void *item) {
    if (!vec) {
        fmt_fprintf(stderr, "Error: Vector is NULL in vector_push_back.\n");
        return false; // Indicate failure
    }

    if (vec->size >= vec->capacitySize) {
        size_t newCapacity = vec->capacitySize * 2; // Example growth
strategy
        // Allocate new space from the memory pool
        void *newItems = memory_pool_allocate(vec->pool, newCapacity *
vec->itemSize);
        if (!newItems) {
            fmt_fprintf(stderr, "Error: Failed to allocate memory in
vector_push_back.\n");
            return false; // Indicate failure
        }

        memcpy(newItems, vec->items, vec->size * vec->itemSize); // Copy
existing items to the new space
        vec->items = newItems;
        vec->capacitySize = newCapacity;
    }

    // Proceed with adding the new item
    memcpy((char *)vec->items + (vec->size * vec->itemSize), item,
vec->itemSize);
    vec->size++;
    return true; // Indicate success
}

also now vector_emplace_back return value base on result
bool vector_emplace_back(Vector *vec, void *item, size_t itemSize) {
    if (!vec) {
        fmt_fprintf(stderr, "Error: Vector is NULL in
vector_emplace_back.\n");
        return false; // Indicate failure
    }
    if (itemSize != vec->itemSize) {
        fmt_fprintf(stderr, "Error: Invalid item size in
vector_emplace_back.\n");
        return false; // Indicate failure
    }
    if (vec->size >= vec->capacitySize) {
        if (!vector_reserve(vec, vec->capacitySize * 2)) {
            return false; // vector_reserve failed, indicate failure
        }
    }

    memcpy((char *)vec->items + vec->size * vec->itemSize, item,
vec->itemSize);
    vec->size++;
    return true; // Indicate success
}
