### ISSUE TITLE
JSON considers that if it is not a single value it should be ignored

### ISSUE THREAD

**Issue by HelifeWasTaken** [KaisenAmin/c_std#4]
```cpp
//json.c:621
    if (state.current_token.type == JSON_TOKEN_OBJECT_START) {
        root = parse_object(&state);

    } 
    else if (state.current_token.type == JSON_TOKEN_ARRAY_START) {
        root = parse_array(&state);
    } 
    else {
        fmt_fprintf(stderr, "Error: Root element must be an object or array at position %zu.\n", state.position);
        free(state.input); 
        return NULL;
    }
```
But a json can be valid as a single and unique value
```json
"value"
```
```json
53
```
etc...

**Comment by KaisenAmin** [comment]
Dear Mattis,

Currently, I am engaged in the implementation of JSON and I am aware of the
issue you've mentioned. You are absolutely correct that a JSON can be valid
as a single, unique value, such as a simple string ("value"), a number
(53), etc.
I have some ideas for resolving this issue, but I need some time to
implement them. This matter requires a review and possibly a rewrite of
parts of the JSON parsing code to ensure that various types of JSON values
are properly supported.
As soon as I am able to make these changes, I will be sure to inform you.
Thank you for pointing out this important detail.

Best regards,

**Comment by KaisenAmin** [comment]
now json_parser can handle single value as json.
